### PR TITLE
Support short-hand partial rendering syntax

### PR DESCRIPTION
**Pull request by swalkinshaw**
This PR updates a few things, but mainly adds support for short-hand partial rendering.

Before, only the following syntax was supported:

``` ruby
<%= render partial: 'item', collection: @items, cache: true %>
```

Now, this is also supported:

``` ruby
<%= render @items, cache: true %>
```

Few other minor changes:
- Changed `is_a?(Proc)` to `respond_to?(:call)` for a bit more flexibility.
- Enabled using `cache: false` for easy collection caching toggling.
- Removed some trailing whitespace.
- Added ruby syntax highlighting to docs.

Let me know if you want any of these extra commits removed.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Just noticed there's another PR open (#13) that has some big changes. If you were going to merge both these in, I'd suggest mine first since it would be a lot easier.

**Comment by ryansch** [comment]
This is very useful.

**Comment by n8** [comment]
@swalkinshaw Sorry, can you update the Readme in this pull request so it merges cleanly. I inadvertently merged in another pull request that also added some changes to the Readme for highlighting.

**Comment by swalkinshaw** [comment]
No problem. That highlighting fix was actually better since it used `erb` instead of `ruby` so I've updated and rebased mine to use that.

**Pull request merged**
